### ISSUE TITLE
Site failed to deliver tacos

### ISSUE THREAD

**Issue by cwdcwd** [jayfid/newpointdesigns.com#1]
This website failed to deliver any tacos despite me visiting it on more than one occasion. Pls fix.

**Comment by jayfid** [comment]
Have you tried typing 'taco'?

**Comment by cwdcwd** [comment]
I don't even know how to spell taco. I just smeared guacamole all over the screen and awaited deliver. Site is obviously flawed

**Comment by jayfid** [comment]
Closing issue as duplicate
